# Generated by Django 5.1.4 on 2025-01-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_borrowing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="money_to_pay",
        ),
    ]
