# Generated by Django 5.1.4 on 2025-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_payment_money_to_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
