# Generated by Django 5.1.4 on 2025-01-02 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="daily_free",
            new_name="daily_fee",
        ),
    ]
