name: Test

on:
  pull_request:
    branches:
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          sudo systemctl start redis-server
          sudo systemctl enable redis-server

      - name: Verify Redis is running
        run: redis-cli ping

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run flake8
        run: poetry run flake8

      - name: Run tests
        timeout-minutes: 5
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: poetry run python manage.py test